--- #YAML:1.0
name: RiveScript
abstract: A scripting language for chatbots.
version: 1.34
author:
    - Noah Petherbridge <kirsle@cpan.org>
license: mit
distribution_type: module
requires:
    perl: 5.008000
    JSON: 0
recommends:
    Clone: 0
build_requires:
    Test::More: 0
provides:
    RiveScript:
        file: lib/RiveScript.pm
        version: 1.34
    RiveScript::WD:
        file: lib/RiveScript/WD.pm
        version: 1.34
keywords:
    - chatbot
    - chatterbot
    - alice
    - aiml
    - chatscript
    - artificial intelligence
generated_by: Noah Petherbridge
meta-spec:
    version: 1.4
    url: http://module-build.sourceforge.net/META-spec-v1.4.html
