---
abstract: 'Rendering Intelligence Very Easily'
author:
  - 'Noah Petherbridge <kirsle@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.132140'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RiveScript
no_index:
  directory:
    - t
    - inc
requires:
  JSON: 0
  perl: 5.008000
version: 1.34
